import bcrypt from "bcryptjs";
const data = {
	//users data
	users: [
		{
			name: "John",
			email: "admin@example.com",
			password: bcrypt.hashSync("1234567"),
			isAdmin: true,
		},
		{
			name: "Jane",
			email: "user@example.com",
			password: bcrypt.hashSync("1234567"),
			isAdmin: false,
		},
		{
			name: "Yaw",
			email: "yaw@example.com",
			password: bcrypt.hashSync("1234567"),
			isAdmin: false,
		},
	],

	//products data
	products: [
		{
			name: "Free shirt",
			slug: "free-shirt",
			category: "Shirts",
			image: "/images/shirt_1.jpg",
			price: 80,
			brand: "Polo",
			rating: 4.0,
			numReviews: 10,
			countInStock: 15,
			description: "A popular shirt",
		},
		{
			name: "Fit shirts",
			slug: "fit-shirt",
			category: "Shirts",
			image: "/images/shirt_5.jpg",
			price: 60,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "A popular shirt",
		},
		{
			name: "Golf pants",
			slug: "golf-pants",
			category: "Pants",
			image: "/images/pant_3.png",
			price: "90",
			brand: "Oliver",
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: "A smart looking pant",
		},
		{
			name: "Fit Pant",
			slug: "fit-pants",
			category: "Pant",
			image: "/images/golf.jpg",
			price: 95,
			brand: "Zora",
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: "A popular pant",
		},
		{
			name: "Classic Shirt",
			slug: "classic-shirt",
			category: "Clothing and Acccesories",
			image: "/images/shirt_3.jpg",
			price: 70,
			brand: "Oliver",
			rating: 4.5,
			numReviews: 10,
			countInStock: 15,
			description: "A popular shirt",
		},
		{
			name: "Nike shoe",
			slug: "nike-shoe",
			category: "Clothing and Acccesories",
			image: "/images/Nike shoe.jpg",
			price: 70,
			brand: "Nike",
			rating: 3.8,
			numReviews: 10,
			countInStock: 14,
			description: "A popular shoe",
		},
		{
			name: "Adidas shoe",
			slug: "adidas shoe",
			category: "Clothing and Acccesories",
			image: "/images/adidas.jpg",
			price: 70,
			brand: "Addidas",
			rating: 5.0,
			numReviews: 10,
			countInStock: 19,
			description: "adidas shoes range online",
		},
		{
			name: "Wallabees",
			slug: "wallabees-shoes",
			category: "Clothing and Acccesories",
			image: "/images/Wallabees.jpg",
			price: 70,
			brand: "Wallabees",
			rating: 2.5,
			numReviews: 10,
			countInStock: 20,
			description: "Clarks Men's Wallabee Shoe",
		},
		{
			name: "Bluetooth speakers",
			slug: "speaker",
			category: "Electronics",
			image: "/images/speaker.jpg",
			price: 80,
			brand: "Nike",
			rating: 3.5,
			numReviews: 10,
			countInStock: 20,
			description:
				"Creative T15 Wireless - 2.0 Bluetooth Wireless Speakers - Creative Labs",
		},
		{
			name: "Delron rice cooker",
			slug: "rice-cooker",
			category: "Appliances",
			image: "/images/cooker.jpg",
			price: 70,
			brand: "Delron",
			rating: 4.5,
			numReviews: 10,
			countInStock: 30,
			description: "A quality cooker for your home",
		},
		{
			name: "Hisense Electric kettle",
			slug: "kettle",
			category: "Appliance",
			image: "/images/kettle.jpg",
			price: 70,
			brand: "Hisense",
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: "A popular shoe",
		},
		{
			name: "Nasco Blender",
			slug: " blender",
			category: "Appliances",
			image: "/images/blender.jpg",
			price: 100,
			brand: "Nasco",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description:
				"NutriBullet ZNBF30400Z Blender 1200 Watts, 1200W, Dark Gray",
		},
	],
};

export default data;
