const data = {
	products: [
		{
			name: "Free shirts",
			slug: "free-shirt",
			category: "Shirts",
			image: "/images/shirt_1.jpg",
			price: "70",
			brand: "Nike",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "A popular shirt",
		},
		{
			name: "Fit shirts",
			slug: "fit-shirt",
			category: "Shirts",
			image: "/images/shirt_5.jpg",
			price: "60  ",
			brand: "Adidas",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "A popular shirt",
		},
		{
			name: "Golf pants",
			slug: "golf-pants",
			category: "Pants",
			image: "/images/pant_3.png",
			price: "90",
			brand: "Oliver",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "A smart looking pant",
		},
		{
			name: "Fit Pant",
			slug: "fit-pants",
			category: "Pant",
			image: "/images/golf.jpg",
			price: "95",
			brand: "Zora",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "A popular pant",
		},
		{
			name: "Classic Shirt",
			slug: "classic-shirt",
			category: "Pant",
			image: "/images/shirt_3.jpg",
			price: "70",
			brand: "Nike",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "A popular shirt",
		},
		{
			name: "Nike shoe",
			slug: "nike-shoe",
			category: "Pant",
			image: "/images/Nike shoe.jpg",
			price: "70",
			brand: "Nike",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "A popular shoe",
		},
		{
			name: "Adidas shoe",
			slug: "adidas shoe",
			category: "Pant",
			image: "/images/adidas.jpg",
			price: "70",
			brand: "Nike",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "adidas shoes range online",
		},
		{
			name: "Wallabees",
			slug: "wallabees-shoes",
			category: "Pant",
			image: "/images/Wallabees.jpg",
			price: "70",
			brand: "Nike",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "Clarks Men's Wallabee Shoe",
		},
		{
			name: "Bluetooth speakers",
			slug: "speaker",
			category: "Pant",
			image: "/images/speaker.jpg",
			price: "70",
			brand: "Nike",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description:
				"Creative T15 Wireless - 2.0 Bluetooth Wireless Speakers - Creative Labs",
		},
		{
			name: "Delron rice cooker",
			slug: "rice-cooker",
			category: "Pant",
			image: "/images/cooker.jpg",
			price: "70",
			brand: "Nike",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "A quality cooker for your home",
		},
		{
			name: "Hisense Electric kettle",
			slug: "classic-shirt",
			category: "Appliance",
			image: "/images/kettle.jpg",
			price: "70",
			brand: "Nike",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description: "A popular shoe",
		},
		{
			name: "Nasco Blender",
			slug: "classic-shirt",
			category: "Pant",
			image: "/images/blender.jpg",
			price: "70",
			brand: "Nike",
			rating: "4.5",
			numReviews: "10",
			countInStock: "20",
			description:
				"NutriBullet ZNBF30400Z Blender 1200 Watts, 1200W, Dark Gray",
		},
	],
};

export default data;
